trigger: none

pool:
  name: Default

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:

    - script: |
        echo "Creating artifact folder..."
        echo "DevOps Artifact" > $(Build.ArtifactStagingDirectory)/app.txt
      displayName: Create Artifact

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: Publish Artifact


- stage: Dev
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - script: echo "Deploying to DEV environment (mock)"
      displayName: Dev Deploy


- stage: QAT
  displayName: Deploy to QAT
  dependsOn: Dev
  jobs:
  - job: QATDeploy
    steps:
    - script: echo "Deploying to QAT environment (mock)"
      displayName: QAT Deploy


- stage: Staging
  displayName: Deploy to Staging
  dependsOn: QAT
  jobs:
  - job: StagingDeploy
    steps:
    - script: echo "Deploying to STAGING environment (mock)"
      displayName: Staging Deploy


- stage: Production
  displayName: Deploy to Production
  dependsOn: Staging
  jobs:
  - job: ProdDeploy
    steps:
    - script: echo "Deploying to PRODUCTION environment (mock)"
      displayName: Deploying